### ISSUE TITLE
5.4.2: No connection to fhem server after update

### ISSUE THREAD

**Issue by janusjanusjanus** [klassm/andFHEM#1316] opened 2019-03-03 11:44 UTC
After updating to 5.4.2 the app shows "Keine Verbindung zum FHEM-Server"
Tested on two devices (Samsung Galaxy Tab, Redmi 3S) with the same result.

**Comment by klassm** [comment] 2019-03-03 11:45
Well - that's stange. There was no change on anything affecting the connection. Can you send app logs to see what happens in andFHEM?

**Comment by janusjanusjanus** [comment] 2019-03-03 11:50
done.

**Comment by klassm** [comment] 2019-03-03 12:07
Fixed with #1317 
Will release an update asap. If this still happens afterwards, please open the issue again. From the logs I got this should be the solution - unfortunately I was not able to reproduce this, so I am not 100% sure.

**Closed by klassm** 2019-03-03 12:07 UTC

**Comment by janusjanusjanus** [comment] 2019-03-03 23:54
Thank you very much!
I've just bought andFHEM.
I don't need any of the premiun functions, but I like the way how fast you handle issues!

**Comment by klassm** [comment] 2019-03-04 05:20
Well it was my fault ;-). But thanks!
