### ISSUE TITLE
Freeze on Open

### ISSUE THREAD

**Issue by akidburn** [klassm/andFHEM#1140] opened 2017-07-30 13:16 UTC
Hi,

when opening the app and trying to refresh the app freezes. sometimes i see some devices, but the freeze occurs within a few seconds of the app opening. 

the longest working period was after reentering the config for the fhem server, and after saving and refreshing, this was the only time i saw some devices. every other time the app froze while refreshing.

I have two devices, one Android 4.4 and one Android 5.1.1,
both are affected by this.

andFHEM is version 4.6.2

**Comment by klassm** [comment] 2017-07-30 13:22
Hi,

Sorry for that. Actually, this issue is pretty strange, as I cannot reproduce this on my configuration here. I even tried to set up the app from scratch - no freeze. Can you try to reinstall the app and try whether you can open up the app afterwards?

Sorry...
Matthias

**Comment by klassm** [comment] 2017-07-30 14:06
After playing around a little more I found two different bugs - but still no application freeze...

**Comment by klassm** [comment] 2017-08-20 08:43
Do you still encounter this issue? Otherwise I'd close this issue here.

**Closed** 2017-09-16 09:38 UTC
